### ISSUE TITLE
Problems using volumes and/or data-only containers.

### ISSUE THREAD

**Issue by smyrman** [Docker-nano/Ghost#1]
The docs states "Ghost's content directory is mapped to /var/ghost and can be mirrored to the host using volumes."
I would expect this means i could mount a volume on "/var/ghost" in the container, but that doesn't seam to work...

Steps to reproduce:

```
$ mkdir tmp
$ chmod a+rwx tmp
$  docker run --volume "$PWD/tmp:/var/ghost" nano/ghost 
```

Same results for using local folder or data-only container inheriting from busybox.

This results in:
- Failing to open database

```
Migrations: Database initialisation required for version 003
Migrations: Creating tables...
Migrations: Creating table: posts
Possibly unhandled Error: SQLITE_CANTOPEN: unable to open database file
```

Expected results:
- DB migrations passing on first run:

```
Migrations: Database initialisation required for version 003
Migrations: Creating tables...
Migrations: Creating table: posts
Migrations: Creating table: users
Migrations: Creating table: roles
Migrations: Creating table: roles_users
Migrations: Creating table: permissions
Migrations: Creating table: permissions_users
Migrations: Creating table: permissions_roles
Migrations: Creating table: permissions_apps
Migrations: Creating table: settings
Migrations: Creating table: tags
Migrations: Creating table: posts_tags
Migrations: Creating table: apps
Migrations: Creating table: app_settings
Migrations: Creating table: app_fields
Migrations: Creating table: clients
Migrations: Creating table: accesstokens
Migrations: Creating table: refreshtokens
Migrations: Populating fixtures
Migrations: Populating permissions
Migrations: Creating owner
Migrations: Populating default settings
Migrations: Complete
Ghost is running... 
Your blog is now available on http://my-ghost-blog.com 
Ctrl+C to shut down
```
- DB migrations skipped on second run:

```
Migrations: Up to date at version 003
Ghost is running in development... 
Listening on 0.0.0.0:2368 
Url configured as: http://localhost:2368 
Ctrl+C to shut down                     
```

**Comment by Bilge** [comment]
Probably because the daemon does not have write permissions on whatever `$PWD/tmp` maps to.

**Comment by smyrman** [comment]
Are you referring to the docker daemon? It has full permission to read the directory...Or are you referring to another daemon service?

It works perfectly well with the official docker ghost image to do this (using /var/lib/ghost, which is what they uses). That's where I got the expected output from.

**Comment by Bilge** [comment]
By daemon I am referring specifically to `/usr/bin/ghost` (node) running in the container. I'm not really sure why file permissions would ever be an issue since the daemon runs as root and Docker also runs as root but I don't know what else to suggest. I am running this image in production using similar volume mapping so all I can tell you is that it works for me.

**Comment by smyrman** [comment]
Ok. I moved to another blogging platform in the end... I also do not know the caused the issue, but I am fine with you closing it as can not reproduce.
